apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: comet
  source:
    repoURL: https://github.com/ajits7/argo-cd-app-of-apps-demo.git
    targetRevision: HEAD
    path: charts/cr
    helm:
      releaseName: crb
      valueFiles:
        - /charts/crb/values.yaml
  destination:
    name: in-cluster
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true