apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crb
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: general
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: comet
  source:
    repoURL: https://github.com/ajits7/argo-sample.git
    targetRevision: HEAD
    path: charts/crb
    helm:
      releaseName: crb
      valueFiles:
        - /charts/crb/values.yaml
  destination:
    name: in-cluster
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true