# Description: Prometheus application for ArgoCD############################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: comet
  sources:
    - repoURL: https://github.com/ajits7/argo-sample.git
      targetRevision: HEAD
      ref: <customizable reference>
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: 19.7.2
      helm:
        values: |
            server:
              service:
                type: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  
# ############################## END OF prometheus.yaml ####################################