apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-devops
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: devops
  source:
    path: argocd-apps/devops/
    repoURL: https://github.com/ajits7/argo-cd-app-of-apps-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true