---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  slack-token: xoxb-9191207266-6338619634979-43XtUUS89kVgBoNDTui9kKV5
  # slack-token: eG94Yi05MTkxMjA3MjY2LTYzMzg2MTk2MzQ5NzktNDNYdFVVUzg5a1ZnQm9ORFR1aTlrS1Y1