apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: comet
  source:
    repoURL: https://github.com/ajits7/argo-sample.git
    targetRevision: HEAD
    path: automation/helm-releases/argo-cd
    helm:
      releaseName: argo-cd
      valueFiles:
        - /automation/helm-releases/argo-cd/values.yaml
  destination:
    name: in-cluster
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true