# varnish-operator:
#   replicas: 1
#   # monitoring:
#   #   prometheusServiceMonitor:
#   #     enabled: true
#   #   grafanaDashboard:
#   #     datasourceName: Prometheus
#   #     enabled: true
#   #     namespace: prometheus-operator
#   container:
#     imagePullPolicy: Always
#     restartPolicy: Always
#     resources:
#       limits:
#         cpu: 200m
#         memory: 200Mi
#       requests:
#         cpu: 200m
#         memory: 200Mi
#     metricsPort: 9131
#     webhookPort: 9244
#     logLevel: info
#     logFormat: json