apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: devops
  source:
    path: automation/helm-releases/argo-cd
    repoURL: https://github.com/ajits7/argo-cd-app-of-apps-demo.git
    targetRevision: HEAD